version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./uploads:/usr/share/nginx/html/uploads

  app:
    build:
      context: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - db

  db:
    image: sqlite
    volumes:
      - ./carros.db:/data/carros.db